volumes:
  logger-aop-db-pg:

services:
  slogger-aop-db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: log
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logger-aop-db
    volumes:
      - logger-aop-db-pg:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      suppliercosumer:

networks:
  suppliercosumer: